# -*- coding: utf-8 -*-
"""
Created on Tue Jun 23 08:32:26 2020

@author: Tuli
"""

# -*- coding: utf-8 -*-
"""
Created on Tue Jun 23 07:21:24 2020

@author: Tuli
"""

balance = 999999
annualInterestRate = 0.18

monthlyInterestRate = annualInterestRate / 12
maxMonthlyPayment = (balance * (1 + annualInterestRate / 12)**12 ) / 12
minMonthlyPayment = balance / 12

def payingDebtOff1Year(balance, annualInterestRate, maxMonthlyPayment, minMonthlyPayment, months = 12):
    '''
    balance - the outstanding balance on the credit card
    annualInterestRate - annual interest rate as a decimal
    maxMonthlyPayment - autogenerated
    minMonthlyPayment - autogenerated
    months - default amount for 1 year debt payoff
    '''
    #defining starting value for bisection search
    monthlyPayment = (maxMonthlyPayment + minMonthlyPayment) / 2
    
    #calculating debt left after 1 year
    currentBalance = balance
    while months >= 1:
        monthlyUnpaidBalance = currentBalance - monthlyPayment
        currentBalance = monthlyUnpaidBalance + monthlyInterestRate * monthlyUnpaidBalance
        months -= 1
        
    #checking if balance is positive, if yes change minMonthlyPayment, start over, continuing the bisection
    if currentBalance >= 0:
        return payingDebtOff1Year(balance, annualInterestRate, maxMonthlyPayment, monthlyPayment, months = 12)
    
    #balance was negative, so we are going to calculate the debt with the smallest increase in monthlyPayment
    updatedBalance = balance
    while months >= -11:
        monthlyUnpaidBalance = updatedBalance - monthlyPayment + 0.01
        updatedBalance = monthlyUnpaidBalance + monthlyInterestRate * monthlyUnpaidBalance
        months -= 1
        
    #if this is positive, it means the original payment was the lowest possible payment, our job is done
    if updatedBalance > 0:
        print("Lowest Payment: " + str((round(monthlyPayment, 2))))
        return
    
    #this means second calculation was negative, so we lower the maximum monthly payment to monthly payment and start over, continuing the bisection
    return payingDebtOff1Year(balance, annualInterestRate, monthlyPayment, minMonthlyPayment, months = 12)


payingDebtOff1Year(balance, annualInterestRate, maxMonthlyPayment, minMonthlyPayment, months = 12)